# Generated by Django 4.2.14 on 2024-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Account', max_length=120),
            preserve_default=False,
        ),
    ]
