# Generated by Django 4.2.14 on 2024-08-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('transactions', '0004_remove_category_month_remove_category_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='debts.debt'),
        ),
    ]
