from .environ import env

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": env.str("DJANGO_VAPID_PUBLIC_KEY"),
    "VAPID_PRIVATE_KEY": env.str("DJANGO_VAPID_PRIVATE_KEY"),
    "VAPID_ADMIN_EMAIL": env.str("DJANGO_VAPID_ADMIN_EMAIL"),
}
