# Generated by Django 4.2.14 on 2024-08-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='type',
            field=models.CharField(default='LEND', max_length=4),
            preserve_default=False,
        ),
    ]
