# Generated by Django 5.0.8 on 2024-09-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_name'),
        ('debts', '0003_alter_debt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='type',
            field=models.CharField(choices=[('LEND', 'Yo presto dinero'), ('LOAN', 'Me prestan dinero')], max_length=4, verbose_name='Tipo'),
        ),
    ]
